###############################################################
#
#        欢迎使用XiaoYum - 逍式Yum
#
###############################################################

#阻止执行插件操作的插件名称
Ignore:
  - 'XiaoYum'
  - 'EconomyAPI'
#是否启用delete功能 （禁用则无法使用删除插件与删除插件配置文件功能）
Delete: true

#配置文件版本
Version: 1.0.0